# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Example' do
  # use_frameworks!
  # use_frameworks! :linkage=> :static
  # use_frameworks! :linkage => :dynamic

  config = use_native_modules!

  use_react_native!(
    :path => "../../#{config[:reactNativePath]}", # I've commented out the next line and added this line to resolve the build error caused by the use of use_frameworks! on react-native v0.73.x, due to yoga header path issue, refer here: https://github.com/facebook/react-native/issues/41938#issuecomment-1925888879.
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Note that if you have use_frameworks! enabled, then comment out these lines
    pod 'FirebaseCore', :modular_headers => true
    pod 'GoogleUtilities', :modular_headers => true

    # This is added to resolve the build error. Once we update the MoEngage iOS SDK to the latest version, we can remove this.
    pod 'MoEngage-iOS-SDK', '9.7.0'

    # This is to solve the Rudder-CleverTap build error
    pod 'Rudder-CleverTap', '1.1.2'
    

  target 'ExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # This is to solve "Undefined symbols for architecture x86_64" error
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
        # config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        # XCode 15 issue: https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1653051943 (when use_frameworks! is enabled)
        # xcconfig_path = config.base_configuration_reference.real_path
        # xcconfig = File.read(xcconfig_path)
        # xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        # File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

        # Setting the deployment target to 13.0 to solve the build error
        # config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'

        # XCdoe 15.3 build issue: https://github.com/facebook/react-native/issues/43335#issuecomment-1980708164
        # if target.name == 'Flipper'
        # file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
        # contents = File.read(file_path)
        # unless contents.include?('#include <functional>')
        #   File.open(file_path, 'w') do |file|
        #     file.puts('#include <functional>')
        #     file.puts(contents)
        #   end
        # end
      end
    end
  end
end
