source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.1.0"

gem 'cocoapods', '1.16.2'
gem 'activesupport', '7.2.3.1'
gem 'addressable', '2.9.0'
gem 'concurrent-ruby', '1.3.7'
gem 'json', '2.19.9'
gem 'zeitwerk', '< 2.7'
