name: Check iOS Build

on:
  pull_request:
    branches: ['master']
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    name: Check iOS Build
    runs-on: macos-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: '3.3.2'

      - name: Setup CocoaPods
        uses: maxim-lobanov/setup-cocoapods@8e97e1e98e6ccf42564fdf5622c8feec74199377 #v1
        with:
          version: 1.16.2

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: latest-stable

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install node_modules
        env:
          HUSKY: 0
        run: |
          npm run setup:ci

      - name: Restore Pods cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            apps/example/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('apps/example/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: |
          cd apps/example/ios && \
          pod install --repo-update && \
          cd .. && \
          cd .. && \
          cd ..

      - name: Bundle apps
        run: |
          npm run bundle:ci

      - name: Add GoogleService-Info.plist
        run: |
          pwd
          echo '${{secrets.GOOGLESERVICE_INFO_PLIST_FILE}}' > apps/example/ios/GoogleService-Info.plist
          echo "$( < apps/example/ios/GoogleService-Info.plist)"
          cd apps/example/ios
          ls -li

      - name: Xcode Version
        run: |
          xcode-select -p
          /usr/bin/xcodebuild -version

      - name: Execute iOS build check
        run: |
          npm run build:ios:ci
