name: Check Android Build

on:
  pull_request:
    branches: ['develop', 'master']
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    name: Check Android Build
    runs-on: macos-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install node_modules
        env:
          HUSKY: 0
        run: |
          npm run setup:ci

      - name: Add .env file
        run: |
          pwd
          echo '${{secrets.DOT_ENV}}' > apps/example/.env
          echo "$( < apps/example/.env)"
          cd apps/example/
          ls -li

      - name: Bundle apps
        run: |
          npm run bundle:ci

      - name: Execute android build check
        run: |
          npm run build:android
