name: 'Unit Tests, Coverage & Sonar'

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    name: 'Unit Tests, Coverage & Sonar'
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: '3.3.2'

      - name: Setup CocoaPods
        uses: NiftyStack/install-cocoapods-action@d886e873d6cb61e14ef64a31ce8615f3c0f18c85 #1.0.1

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        env:
          HUSKY: 0
        run: |
          npm run setup:ci

      - name: Setup .env file
        run: |
          cat <<EOF > apps/example/.env
            TEST_WRITE_KEY=${{ secrets.TEST_WRITE_KEY }}
            TEST_DATAPLANE_URL=${{ secrets.TEST_DATAPLANE_URL }}
           EOF

      - name: Execute linting tests
        run: |
          npm run check:lint:ci

      - name: Execute unit tests
        run: |
          npm run test:ci

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
